name: Back up database

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

permissions:
  contents: write

jobs:
  backup:
    name: Back up database
    runs-on: self-hosted
    timeout-minutes: 15
    outputs:
      branch-name: ${{ steps.commit.outputs.branch-name }}
      update-condition: ${{ steps.commit.outputs.condition }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Install dependencies
        run: |
          curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash && \
          sudo apt update && \
          sudo apt install -y wget git-lfs && \
          git lfs install && \
          wget -nv https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2404-x86_64-100.13.0.deb && \
          sudo apt install ./mongodb-database-tools-ubuntu2404-x86_64-100.13.0.deb && \
          rm ./mongodb-database-tools-ubuntu2404-x86_64-100.13.0.deb && \
          mongodump --version
      - name: Dump database archive
        run: |
          mkdir -p backup && \
          mongodump --db=arknights --archive=backup/arknights.dump
      - name: Commit database archive
        id: commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config --global http.postBuffer 524288000
          BRANCH_NAME="$(date +'%Y-%m-%d')"
          git checkout -b $BRANCH_NAME
          git add backup/arknights.dump || :
          if git diff --cached --quiet; then
            echo "No changes to commit."
            echo "condition=false" >> $GITHUB_OUTPUT
          else
            git commit -m "backup: $BRANCH_NAME"
            git push -f --set-upstream origin $BRANCH_NAME
            echo "condition=true" >> $GITHUB_OUTPUT
          fi
          echo "branch-name=$BRANCH_NAME" >> $GITHUB_OUTPUT

  pr:
    name: Create pull request
    needs: backup
    if: needs.backup.outputs.update-condition == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Create pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh pr create --title "backup: ${{ needs.backup.outputs.branch-name }}" --body "Merge ${{ needs.backup.outputs.branch-name }} into main" --base main --head ${{ needs.backup.outputs.branch-name }} || :
      - name: Merge pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh pr merge --auto --squash --delete-branch ${{ needs.backup.outputs.branch-name }} || :
